version: "3.8"

networks:
  app-network:
    external: true

services:
  be-trainer:
    build: .
    container_name: be_trainer
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env-sample
    restart: unless-stopped
    networks:
      - app-network
